Nsu.Belov.TrainsDatabase.Web/Models/SelectTicketViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Reinforced.Lattice.Configuration;

namespace Nsu.Belov.TrainsDatabase.Web.Models
{
    public class SelectTicketViewModel
    {
        public int DepartureStationId { get; set; }
        public int ArrivalStationId { get; set; }

        public string Date { get; set; }

        public IEnumerable<SelectListItem> StationNames { get; set; }
        public Configurator<SelectTripRow, SelectTripRow> Configurator { get; set; }
    }

    public class SelectTripRow
    {
        public int TripId { get; set; }
        public int? TrainId { get; set; }
        public int RouteId { get; set; }
        public DateTime? DepartureTime { get; set; }
        public DateTime? ArrivalTime { get; set; }
    }

    public static class SelectTripTable
    {
        public static Configurator<SelectTripRow, SelectTripRow> Configure(
            this Configurator<SelectTripRow, SelectTripRow> conf)
        {
            conf.DefaultTable();
            //conf.Column(c => c.StationId).Title("Id");
            //conf.Column(c => c.StationName).Title("Station Name");
            return conf;
        }
    }
}

Nsu.Belov.TrainsDatabase.Web/Controllers/TicketsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Nsu.Belov.TrainsDatabase.Database;
using Nsu.Belov.TrainsDatabase.Web.Models;
using Reinforced.Lattice.Configuration;
using Reinforced.Lattice.Mvc;

namespace Nsu.Belov.TrainsDatabase.Web.Controllers
{
    public class TicketsController : Controller
    {
        private readonly TrainsDataContext _context;

        public TicketsController(TrainsDataContext context)
        {
            _context = context;
        }

        public ActionResult SelectTrip()
        {
            var firstOrDefault = _context.CrewMembers.FirstOrDefault();
            SelectTicketViewModel stvm = new SelectTicketViewModel()
            {
                StationNames = _context.Stations.Select(x => new SelectListItem()
                    {
                        Text = x.StationName,
                        Value = x.StationId.ToString()
                    }
                )
            };
            return View(stvm);
        }

        public ActionResult SelectTicket(SelectTicketViewModel vm)
        {
            vm.Configurator = new Configurator<SelectTripRow, SelectTripRow>()
                .Configure()
                .Url(Url.Action(nameof(HandleSelTicTable), new
                {
                    depStationId = vm.DepartureStationId,
                    arrStationId = vm.ArrivalStationId,
                    date = vm.Date
                }));
            return View(vm);
        }

        public ActionResult HandleSelTicTable(int depStationId, int arrStationId, string date)
        {
            var conf = new Configurator<SelectTripRow, SelectTripRow>().Configure();
            var handler = conf.CreateMvcHandler(ControllerContext);
            DateTime departureDate =
                DateTime.ParseExact(date, "dd.MM.yyyy", System.Globalization.CultureInfo.InvariantCulture);


            #region SecondVariant

            /* var allDeps = _context.RoutePoints.Where(x => x.StationId == depStationId);
                        var allArrs = _context.RoutePoints.Where(x => x.StationId == arrStationId);
            
                        var fr = from start in allDeps
                                 from end in allArrs.Where(x=>x.RouteId==start.RouteId && start.StationOrder< x.StationOrder).Take(1)
                                 join tr in _context.Trips on end.RouteId equals tr.TripId
                                 from depTime in tr.TripPoints.Where(x=>x.StationOrder==start.StationOrder).Select(d=>d.DepartureTime).Take(1)
                                 from aTime in tr.TripPoints.Where(x=>x.StationOrder==end.StationOrder).Select(d=>d.ArrivalTime).Take(1)
                                where start.StationOrder < end.StationOrder
                                select new SelectTripRow()
                                {
                                    DepartureTime = depTime,
                                    ArrivalTime = aTime,
                                    TravelTime = SqlFunctions.DateDiff("n",aTime,depTime),
                                    RouteId = end.RouteId,
                                    TripId = tr.TripId,
                                    TrainId = tr.Train.TrainId
                                };*/

            #endregion

            var fitRoutes = _context.RoutePoints
                .Where(x => x.StationId == depStationId)
                .Join(_context.RoutePoints
                        .Where(x => x.StationId == arrStationId),
                    rp => rp.RouteId,
                    rp => rp.RouteId,
                    (depRp, arrRp) => new
                    {
                        depRp.RouteId,
                        depStationOrder = depRp.StationOrder,
                        arrStationOrder = arrRp.StationOrder
                    })
                .Where(x => x.depStationOrder < x.arrStationOrder);

            var q = _context.Trips
                .Join(fitRoutes,
                    t => t.Route.RouteId,
                    fr => fr.RouteId,
                    (t, fr) => new SelectTripRow()
                    {
                        TripId = t.TripId,
                        RouteId = t.Route.RouteId,
                        TrainId = t.TrainId,
                        DepartureTime = t.TripPoints
                            .FirstOrDefault(tp => tp.StationOrder == fr.depStationOrder)
                            .DepartureTime,
                        ArrivalTime = t.TripPoints
                            .FirstOrDefault(tp => tp.StationOrder == fr.arrStationOrder)
                            .ArrivalTime
                    })
                .Where(s => DbFunctions.TruncateTime(s.DepartureTime) == departureDate);
            return handler.Handle(q);
        }
    }
}

Nsu.Belov.TrainsDatabase.Web/Views/Tickets/SelectTicket.cshtml
@using Reinforced.Lattice.CellTemplating
@using Reinforced.Lattice.Configuration
@using Reinforced.Lattice.Mvc
@using Reinforced.Lattice.Templates
@model Nsu.Belov.TrainsDatabase.Web.Models.SelectTicketViewModel
@{
    ViewBag.Title = "SelectTicket";
    var conf = Model.Configurator;
    conf.AddUiColumn<string>("Время в пути").ClientExpression("getDuration({DepartureTime},{ArrivalTime})");
    conf.Column(x => x.DepartureTime).Format("`parseDateTime({#});`");
    conf.Column(x => x.ArrivalTime).Format("`parseDateTime({#});`");
}

<h2>BuyTicket</h2>
<script>
    var getDuration = function (from, to) {
        var x = moment(from);
        var y = moment(to);
        return moment.duration(x.diff(y)).locale("ru").humanize();
    }
</script>
<div id="table"></div>

@section scripts {
@*    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.min.js"></script>*@
   
    @* Render our templates *@
    @{ Html.RenderTemplates("lt", "Lattice_Templates_Bootstrap"); }

    @* Instantiate our table and put it to JS window.$$table variable *@
    @Model.Configurator.InitializationScript("table", "window.$$table")
}

Nsu.Belov.TrainsDatabase.Web/Views/Tickets/SelectTrip.cshtml
@model Nsu.Belov.TrainsDatabase.Web.Models.SelectTicketViewModel

@{
    ViewBag.Title = "Select route";
}

<style>
    .editor-datetime { position: relative; }
</style>

<h2>Выберите маршрут и дату</h2>
@using (Html.BeginForm("SelectTicket", "Tickets"))
{
    <div class="form-group">
        <label for="@nameof(Model.DepartureStationId)">Станция отправления</label>
        @Html.DropDownListFor(x => x.DepartureStationId, @Model.StationNames, new {@class = "form-control"})
    </div>
    <div class="form-group">
        <label for="@nameof(Model.ArrivalStationId)">Станция прибытия:</label>
        @Html.DropDownListFor(x => x.ArrivalStationId, @Model.StationNames, new {@class = "form-control"})
    </div>
    <div class="form-group">
        <label for="@nameof(Model.Date)">Дата отправления:</label>
        <div class="editor-datetime">
            @Html.TextBoxFor(x => x.Date, new {@class = "form-control", placeholder = "MM.DD.YYYY"})
        </div>
    </div>
    <input type="submit" class="btn btn-primary"/>
    <script type="text/javascript">
        $(function() {
            $('#@nameof(Model.Date)').datetimepicker({
                format: "DD.MM.YYYY",
                showTodayButton: true
            });
        });
    </script>
}