Nsu.Belov.TrainsDatabase.Web/Controllers/RoutesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Nsu.Belov.TrainsDatabase.Database;
using Nsu.Belov.TrainsDatabase.Database.DatabaseEntities;
using Nsu.Belov.TrainsDatabase.Web.Models;
using Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels;
using Reinforced.Lattice;
using Reinforced.Lattice.Adjustments;
using Reinforced.Lattice.Commands;
using Reinforced.Lattice.Configuration;
using Reinforced.Lattice.Editing;
using Reinforced.Lattice.Mvc;
using Reinforced.Lattice.Processing;

namespace Nsu.Belov.TrainsDatabase.Web.Controllers
{
    public class RoutesController : Controller
    {
        private readonly TrainsDataContext _context;

        public RoutesController(TrainsDataContext context)
        {
            _context = context;
        }

        public ActionResult Routes()
        {
            var vm = new Models.RouteViewModel()
            {
                Configurator = new Configurator<Route, RouteRow>()
                    .Configure()
                    .Url(Url.Action(nameof(HandleRoutes)))
            };
            return View(vm);
        }

        public ActionResult HandleRoutes()
        {
            var conf = new Configurator<Route, RouteRow>().Configure();
            var handler = conf.CreateMvcHandler(ControllerContext);
            handler.AddEditHandler(EditRoute);
            handler.AddCommandHandler("Remove", RemoveRoute);
            return handler.Handle(_context.Routes.OrderBy(x => x.RouteId));
        }

        public TableAdjustment EditRoute(LatticeData<Route, RouteRow> latticeData, RouteRow routeRow)
        {
            Route route;
            if (routeRow.RouteId == 0)
            {
                route = new Route();
                _context.Routes.Add(route);
            }
            else
            {
                route = _context.Routes
                    .FirstOrDefault(x => x.RouteId == routeRow.RouteId);
            }

            route.RouteName = routeRow.RouteName;
            _context.SaveChanges();
            routeRow.RouteId = route.RouteId;
            return latticeData.Adjust(x => x
                .Update(routeRow)
                .Message(LatticeMessage.User("success", "Editing", "Route saved"))
            );
        }

        public TableAdjustment RemoveRoute(LatticeData<Route, RouteRow> latticeData)
        {
            var subj = latticeData.CommandSubject();
            var route = _context.Routes.FirstOrDefault(x => x.RouteId == subj.RouteId);
            _context.Routes.Remove(route);
            _context.SaveChanges();
            return latticeData.Adjust(x => x
                .Remove(subj)
                .Message(LatticeMessage.User("success", "Remove", "Route removed"))
            );
        }

        public ActionResult RoutePointsForRoute(int routeId)
        {
            var vm = new Models.RoutePointViewModel()
            {
                SationsNames = (from station in _context.Stations
                    orderby station.StationId
                    select new SelectListItem()
                    {
                        Text = station.StationName,
                        Value = station.StationName
                    }).ToArray(),
                Configurator = new Configurator<RoutePoint, RoutePointRow>()
                    .Configure()
                    .Url(Url.Action(nameof(HandleRoutePoints), new {routeId}))
            };
            return View(vm);
        }

        public ActionResult HandleRoutePoints(int routeId)
        {
            var conf = new Configurator<RoutePoint, RoutePointRow>().Configure();
            var handler = conf.CreateMvcHandler(ControllerContext);
            handler.AddEditHandler((latticeData, rpRow) => EditRoutePoint(latticeData, rpRow, routeId));
            handler.AddCommandHandler("Remove", RemoveRoutePoint);
            var routePoints = _context.RoutePoints
                .Where(x => x.RouteId == routeId)
                .OrderBy(x => x.StationOrder);
            return handler.Handle(routePoints);
        }


        public TableAdjustment EditRoutePoint(LatticeData<RoutePoint, RoutePointRow> latticeData,
            RoutePointRow routePointRow, int routeId)
        {
            RoutePoint routePoint;
            if (routePointRow.RouteId == 0)
            {
                routePoint = new RoutePoint
                {
                    RouteId = routeId,
                    StationOrder = _context.RoutePoints.Where(x => x.RouteId == routeId)
                                       .Select(x => x.StationOrder)
                                       .DefaultIfEmpty(0)
                                       .Max() + 1
                };
                _context.RoutePoints.Add(routePoint);
            }
            else
            {
                routePoint = _context.RoutePoints
                    .FirstOrDefault(x => x.RouteId == routePointRow.RouteId
                                         && x.StationOrder == routePointRow.StationOrder);
            }

            Station station = _context.Stations.FirstOrDefault(x => x.StationName == routePointRow.StationName);

            if (station == null)
            {
                return latticeData.Adjust(x => x
                    .Message(LatticeMessage.User("failure", "Editing",
                        $"There is no station with name {routePointRow.StationName}"))
                );
            }


            if (_context.RoutePoints.Any(x => x.RouteId == routeId
                                              && x.StationOrder != routePoint.StationOrder
                                              && x.Station.StationId == station.StationId))
            {
                return latticeData.Adjust(x => x
                    .Message(LatticeMessage.User("failure", "Editing",
                        $"The route already has station {station.StationName}"))
                );
            }

            routePoint.Station = station;


            _context.SaveChanges();
            return latticeData.Adjust(x => x
                .Update(routePoint)
                .Message(LatticeMessage.User("success", "Editing", "Route saved"))
            );
        }

        public TableAdjustment RemoveRoutePoint(LatticeData<RoutePoint, RoutePointRow> latticeData)
        {
            var subj = latticeData.CommandSubject();
            if (_context.RoutePoints.Any(x => x.RouteId == subj.RouteId && x.StationOrder == subj.StationOrder + 1))
            {
                return latticeData.Adjust(x => x
                    .Message(LatticeMessage.User("failure", "Remove", "Can not delete point from the middle of route"))
                );
            }

            var routePoint =
                _context.RoutePoints.FirstOrDefault(x => x.RouteId == subj.RouteId
                                                         && x.StationOrder == subj.StationOrder);
            _context.RoutePoints.Remove(routePoint);
            _context.SaveChanges();
            return latticeData.Adjust(x => x
                .Remove(subj)
                .Message(LatticeMessage.User("success", "Remove", "RoutePoint removed"))
            );
        }
    }
}

Nsu.Belov.TrainsDatabase.Web/Controllers/TripsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Nsu.Belov.TrainsDatabase.Database;
using Nsu.Belov.TrainsDatabase.Database.DatabaseEntities;
using Nsu.Belov.TrainsDatabase.Web.Models;
using Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels;
using Reinforced.Lattice;
using Reinforced.Lattice.Adjustments;
using Reinforced.Lattice.Commands;
using Reinforced.Lattice.Configuration;
using Reinforced.Lattice.Editing;
using Reinforced.Lattice.Mvc;
using Reinforced.Lattice.Processing;

namespace Nsu.Belov.TrainsDatabase.Web.Controllers
{
    public class TripsController : Controller
    {
        private readonly TrainsDataContext _context;

        public TripsController(TrainsDataContext context)
        {
            _context = context;
        }

        public ActionResult Index()
        {
            var vm = new TripEditViewModel()
            {
                RouteIds = (from route in _context.Routes
                    orderby route.RouteId
                    select new SelectListItem()
                    {
                        Text = route.RouteId.ToString(),
                        Value = route.RouteId.ToString()
                    }).ToArray(),
                TrainIds = (from train in _context.Trains
                    orderby train.TrainId
                    select new SelectListItem()
                    {
                        Text = train.TrainId.ToString(),
                        Value = train.TrainId.ToString()
                    }).ToArray(),
                Configurator = new Configurator<Trip, TripRow>()
                    .Configure()
                    .Url(Url.Action(nameof(HandleTrips)))
            };
            return View(vm);
        }

        public ActionResult HandleTrips()
        {
            var conf = new Configurator<Trip, TripRow>().Configure();
            var handler = conf.CreateMvcHandler(ControllerContext);
            handler.AddEditHandler(EditTrip);
            handler.AddCommandHandler("Remove", RemoveTrip);
            return handler.Handle(_context.Trips);
        }

        public TableAdjustment EditTrip(LatticeData<Trip, TripRow> latticeData, TripRow tripRow)
        {
            Trip trip;
            if (tripRow.TripId == 0)
            {
                trip = new Trip();
                _context.Trips.Add(trip);
            }

            else
            {
                trip = _context.Trips
                    .FirstOrDefault(x => x.TripId == tripRow.TripId);
            }

            //на всякий случай(по идее, если сделано через форму то никогда не сработает)
            if (!_context.Routes.Any(x => x.RouteId == tripRow.RouteId))
            {
                return latticeData.Adjust(x => x
                    .Message(LatticeMessage.User("failure", "Editing",
                        $"There is no route with id {tripRow.RouteId}"))
                );
            }

            if (!_context.Trains.Any(x => x.TrainId == tripRow.TrainId))
            {
                return latticeData.Adjust(x => x
                    .Message(LatticeMessage.User("failure", "Editing",
                        $"There is no train with id {tripRow.TrainId}"))
                );
            }

            trip.RouteId = tripRow.RouteId;
            trip.TrainId = tripRow.TrainId;
            _context.SaveChanges();
            return latticeData.Adjust(x => x
                .Update(trip)
                .Message(LatticeMessage.User("success", "Editing", "Trip saved"))
            );
        }

        public TableAdjustment RemoveTrip(LatticeData<Trip, TripRow> latticeData)
        {
            var subj = latticeData.CommandSubject();
            var trip = _context.Trips.FirstOrDefault(x => x.TripId == subj.TripId);
            _context.Trips.Remove(trip);
            _context.SaveChanges();
            return latticeData.Adjust(x => x
                .Remove(subj)
                .Message(LatticeMessage.User("success", "Remove", "Trip removed"))
            );
        }

        public ActionResult TripPointsForTrip(int tripId)
        {
            var vm = new TripPointForViewModel()
            {
                Configurator = new Configurator<TripPoint, TripPointForRow>()
                    .Configure()
                    .Url(Url.Action(nameof(HandleTripPoints), new {tripId = tripId}))
            };
            return View(vm);
        }

        public ActionResult HandleTripPoints(int tripId)
        {
            var conf = new Configurator<TripPoint, TripPointForRow>().Configure();
            var handler = conf.CreateMvcHandler(ControllerContext);
            handler.AddEditHandler((data, row) => EditTripPoint(data, row, tripId));
            handler.AddCommandHandler("Remove", RemoveTripPoint);
            return handler.Handle(_context.TripPoints.Where(point => point.TripId == tripId));
        }


        public TableAdjustment EditTripPoint(LatticeData<TripPoint, TripPointForRow> latticeData,
            TripPointForRow tripPointRow, int tripId)
        {
            TripPoint tripPoint;
            if (tripPointRow.TripId == 0)
            {
                tripPoint = new TripPoint()
                {
                    TripId = tripId,
                    StationOrder = _context.TripPoints.Where(x => x.TripId == tripId).Max(x => x.StationOrder) + 1
                };
                int routeId = _context.Trips.FirstOrDefault(t => t.TripId == tripId).RouteId;
                if (_context.RoutePoints.Where(rp => rp.RouteId == routeId)
                    .Any(rp => rp.StationOrder == tripPoint.StationOrder))
                {
                    _context.TripPoints.Add(tripPoint);
                }
                else
                {
                    return latticeData.Adjust(x => x
                        .Message(LatticeMessage.User("failure", "Editing",
                            "There are not more stationsin the route"))
                    );
                }
            }
            else
            {
                tripPoint = _context.TripPoints
                    .FirstOrDefault(x => x.TripId == tripId && x.StationOrder == tripPointRow.StationOrder);
            }

            Delay delay = tripPoint.Delay;
            if (tripPointRow.DelayinMinutes.HasValue && tripPointRow.DelayinMinutes != 0)
            {
                if (delay != null)
                {
                    delay.MinutesDelaySpan = tripPointRow.DelayinMinutes.Value;
                }
                else
                {
                    tripPoint.Delay = new Delay()
                    {
                        TripPoint = tripPoint,
                        MinutesDelaySpan = tripPointRow.DelayinMinutes.Value
                    };
                }
            }
            else
            {
                if (delay != null)
                {
                    _context.Delays.Remove(delay);
                }
            }

            if (tripPointRow.DepartureTime.HasValue
                && tripPointRow.ArrivalTime.HasValue
                && tripPointRow.DepartureTime < tripPointRow.ArrivalTime)
            {
                return latticeData.Adjust(x => x
                    .Message(LatticeMessage.User("failure", "Editing",
                        "Depatrure time can not be less then ArrivialTime"))
                );
            }

            if (tripPoint.StationOrder > 1
                && tripPointRow.ArrivalTime.HasValue)
            {
                TripPoint previousPoint = _context.TripPoints
                    .FirstOrDefault(x => x.TripId == tripId && x.StationOrder == tripPointRow.StationOrder - 1);
                if (previousPoint != null && tripPointRow.ArrivalTime < previousPoint.DepartureTime)
                {
                    return latticeData.Adjust(x => x
                        .Message(LatticeMessage.User("failure", "Editing",
                            "Arrivial time less then previous departure"))
                    );
                }
            }

            try
            {
                tripPoint.DepartureTime = tripPointRow.DepartureTime;
                tripPoint.ArrivalTime = tripPointRow.ArrivalTime;
                _context.SaveChanges();
            }
            catch (Exception e)
            {
                return latticeData.Adjust(x => x
                    .Message(LatticeMessage.User("failure", "Editing", $"Save exception: {e.Message}"))
                );
            }

            tripPointRow.TripId = tripPoint.TripId;

            var mpd = latticeData.Configuration.MapRange(latticeData.Source.Where(tp =>
                tp.TripId == tripPoint.TripId && tp.StationOrder == tripPoint.StationOrder));

            return latticeData.Adjust(x => x.Update(mpd)
                .Message(LatticeMessage.User("success", "Editing", "TripPoint saved"))
            );
        }

        public TableAdjustment RemoveTripPoint(LatticeData<TripPoint, TripPointForRow> latticeData)
        {
            var subj = latticeData.CommandSubject();
            if (_context.TripPoints.Any(x => x.TripId == subj.TripId && x.StationOrder == subj.StationOrder + 1))
            {
                return latticeData.Adjust(x => x
                    .Message(LatticeMessage.User("failure", "Remove", "Can not delete point from the middle of route"))
                );
            }

            var tripPoint = _context.TripPoints
                .FirstOrDefault(x => x.TripId == subj.TripId && x.StationOrder == subj.StationOrder);

            _context.TripPoints.Remove(tripPoint);
            _context.SaveChanges();
            return latticeData.Adjust(x => x
                .Remove(subj)
                .Message(LatticeMessage.User("success", "Remove", "RoutePoint removed"))
            );
        }
    }
}

Nsu.Belov.TrainsDatabase.Web/Views/Trips/Index.cshtml
@using Nsu.Belov.TrainsDatabase.Web.Models
@using Reinforced.Lattice.CellTemplating
@using Reinforced.Lattice.Commands
@using Reinforced.Lattice.Configuration
@using Reinforced.Lattice.Editing.Editors.PlainText
@using Reinforced.Lattice.Editing.Editors.SelectList
@using Reinforced.Lattice.Editing.Form
@using Reinforced.Lattice.Filters
@using Reinforced.Lattice.Filters.Range
@using Reinforced.Lattice.Filters.Value
@using Reinforced.Lattice.Mvc
@using Reinforced.Lattice.Plugins.Toolbar
@using Reinforced.Lattice.Templates
@model TripEditViewModel

@{
    ViewBag.Title = "Расписание поездок";
    var conf = Model.Configurator;
    conf.Column(x => x.TripId)
        .Razor(@<div>
                   {TripId} <br>
                   <a href="@Url.Action("TripPointsForTrip", "Trips", new {tripId = "{TripId}"})"> открыть</a>
               </div>);
    conf.Column(x => x.RouteId)
        .Razor(@<div>
                   {RouteId} <br>
                   <a href="@Url.Action("RoutePointsForRoute", "Routes", new {routeId = "{RouteId}"})">открыть</a>
               </div>);

    conf.Column(x => x.DepatrureDate).Format("`parseDateTime({#})`");
    conf.Column(x => x.ArrivalDate).Format("`parseDateTime({#})`");
    conf.EditingForm(f =>
    {
        f.EditSelectList(x => x.RouteId).Items(Model.RouteIds);
        f.EditSelectList(x => x.TrainId).Items(Model.TrainIds);
        f.RenderTo("#ltcModal");
    }, c => c.Event("click").Selector("._beginEdit"));
    conf.Toolbar("toolbar-rt", x => { x.AddSimpleButton("Add new").AddNewByForm(); });
    conf.AddUiColumn<string>("Actions")
        .Razor(@<div>
                   <button class="btn btn-xs btn-warning _beginEdit">
                       <span class="glyphicon glyphicon-pencil"></span>
                   </button>
                   <button class="btn btn-xs btn-danger _remove">
                       <span class="glyphicon glyphicon-remove"></span>
                   </button>
               </div>)
        .SubscribeCellEvent(x => x.Command("click", "Remove").Selector("._remove"))
        ;
    conf.Command("Remove", x => x.ConfigureRemoval());

    conf.Column(x => x.TripId).FilterValueUi(ui => ui.ClientFiltering());
    conf.Column(x => x.TrainId).FilterValueUi(ui => ui.ClientFiltering());
    conf.Column(x => x.RouteId).FilterValueUi(ui => ui.ClientFiltering());
    conf.Column(x => x.RouteName).FilterValueUi(ui => ui.ClientFiltering());
    conf.Column(x => x.DepatrureStationName).FilterValueUi(ui => ui.ClientFiltering());
    conf.Column(x => x.DepatrureDate).FilterValueUi(ui => ui.CompareOnlyDates().ClientFiltering());
    conf.Column(x => x.ArrivalStationName).FilterValueUi(ui => ui.ClientFiltering());
    conf.Column(x => x.ArrivalDate).FilterValueUi(ui => ui.CompareOnlyDates().ClientFiltering());
}

<h2>Маршруты</h2>
<div id="table"></div>

@section scripts {
    @{ Html.RenderPartial("DeleteTemplate"); }
    @* Render our templates *@
    @{ Html.RenderTemplates("lt", "Lattice_Templates_Bootstrap"); }

    @* Instantiate our table and put it to JS window.$$table variable *@
    @Model.Configurator.InitializationScript("table", "window.$$table")
}

Nsu.Belov.TrainsDatabase.Web/Views/Trips/TripPointsForTrip.cshtml
@using Nsu.Belov.TrainsDatabase.Web.Models
@using Reinforced.Lattice.CellTemplating
@using Reinforced.Lattice.Commands
@using Reinforced.Lattice.Configuration
@using Reinforced.Lattice.Editing.Editors.PlainText
@using Reinforced.Lattice.Editing.Form
@using Reinforced.Lattice.Filters
@using Reinforced.Lattice.Filters.Value
@using Reinforced.Lattice.Mvc
@using Reinforced.Lattice.Plugins.Toolbar
@using Reinforced.Lattice.Templates
@model TripPointForViewModel

@{
    ViewBag.Title = "TripPointsForTrip";

    var conf = Model.Configurator;
    conf.Column(x => x.DepartureTime).Format("`parseDateTime({#})`");
    conf.Column(x => x.ArrivalTime).Format("`parseDateTime({#})`");
    conf.EditingForm(f =>
    {
        f.EditPlainText(x => x.ArrivalTime);
        f.EditPlainText(x => x.DepartureTime);
        f.EditPlainText(x => x.DelayinMinutes);
        f.RenderTo("#ltcModal");
    }, c => c.Event("click").Selector("._beginEdit"));
    conf.Toolbar("toolbar-rt", x => { x.AddSimpleButton("Add new").AddNewByForm(); });
    conf.AddUiColumn<string>("Actions")
        .Razor(@<div>
                   <button class="btn btn-xs btn-warning _beginEdit">
                       <span class="glyphicon glyphicon-pencil"></span>
                   </button>
                   <button class="btn btn-xs btn-danger _remove">
                       <span class="glyphicon glyphicon-remove"></span>
                   </button>
               </div>)
        .SubscribeCellEvent(x => x.Command("click", "Remove").Selector("._remove"));
    conf.Command("Remove", x => x.ConfigureRemoval());

    conf.Column(x => x.TripId).FilterValueUi(ui => ui.ClientFiltering());
    conf.Column(x => x.StationOrder).FilterValueUi(ui => ui.ClientFiltering());
    //    conf.Column(x => x.StationName).FilterValueUi(ui => ui.ClientFiltering());
    conf.Column(x => x.DepartureTime).FilterValueUi(ui => ui.CompareOnlyDates().ClientFiltering());
    conf.Column(x => x.ArrivalTime).FilterValueUi(ui => ui.CompareOnlyDates().ClientFiltering());
    conf.Column(x => x.FirstClassSeatsLeft).FilterValueUi(ui => ui.ClientFiltering());
    conf.Column(x => x.SecondClassSeatsLeft).FilterValueUi(ui => ui.ClientFiltering());
    conf.Column(x => x.DelayinMinutes).FilterValueUi(ui => ui.ClientFiltering());
}
<h2>TripPointsForTrip</h2>

<div id="table"></div>

@section scripts {
    @{ Html.RenderPartial("DeleteTemplate"); }
    @* Render our templates *@
    @{ Html.RenderTemplates("lt", "Lattice_Templates_Bootstrap"); }

    @* Instantiate our table and put it to JS window.$$table variable *@
    @Model.Configurator.InitializationScript("table", "window.$$table")
}