Nsu.Belov.TrainsDatabase.Web/Models/CrudViewModels/RouteViewModel.cs
using Nsu.Belov.TrainsDatabase.Database.DatabaseEntities;
using Reinforced.Lattice.Configuration;

namespace Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels
{
    public class RouteViewModel
    {
        public Configurator<Route, Route> Configurator { get; set; }
    }
   

    public static class RouteTable
    {
        public static Configurator<Route, Route> Configure(this Configurator<Route, Route> conf)
        {
            conf.DefaultTable();
            conf.PrimaryKey(x => x.RouteId);
            conf.NotAColumn(x=>x .RoutePoints);
            return conf;
        }
    }
}

Nsu.Belov.TrainsDatabase.Web/Models/CrudViewModels/StationViewModel.cs
using Nsu.Belov.TrainsDatabase.Database.DatabaseEntities;
using Reinforced.Lattice.Configuration;

namespace Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels
{
    public class StationViewModel
    {
        public Configurator<Station, Station> Configurator { get; set; }
    }

    public static class StationTable
    {
        public static Configurator<Station, Station> Configure(this Configurator<Station, Station> conf)
        {
            conf.DefaultTable();
            conf.PrimaryKey(x => x.StationId);
            return conf;
        }
    }
}

Nsu.Belov.TrainsDatabase.Web/Models/CrudViewModels/TrainViewModel.cs
using Nsu.Belov.TrainsDatabase.Database.DatabaseEntities;
using Reinforced.Lattice.Configuration;

namespace Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels
{
    public class TrainViewModel
    {
        public Configurator<Train, Train> Configurator { get; set; }
    }

   
    public static class TrainTable
    {
        public static Configurator<Train, Train> Configure(this Configurator<Train, Train> conf)
        {
            conf.DefaultTable();
            conf.PrimaryKey(x => x.TrainId);
            conf.NotAColumn(train => train.CrewMembers);
            conf.NotAColumn(train => train.Trips);
            return conf;
        }
    }
}

Nsu.Belov.TrainsDatabase.Web/Models/CrudViewModels/TripPointViewModel.cs
using System.Linq;
using Nsu.Belov.TrainsDatabase.Database.DatabaseEntities;
using Reinforced.Lattice.Configuration;

namespace Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels
{
    public class TripPointViewModel
    {
        public Configurator<TripPoint, TripPoint> Configurator { get; set; }
    }

    public static class TripPointTable
    {
        public static Configurator<TripPoint, TripPoint> Configure(
            this Configurator<TripPoint, TripPoint> conf)
        {
            conf.DefaultTable();
            conf.PrimaryKey(x => new {x.TripId, x.StationOrder});
            conf.NotAColumn(c => c.Delay);
            conf.NotAColumn(c => c.TicketsFromHere);
            conf.NotAColumn(c => c.TicketsToHere);
            return conf;
        }
    }
}

Nsu.Belov.TrainsDatabase.Web/Models/CrudViewModels/TripViewModel.cs
using System;
using System.Linq;
using Nsu.Belov.TrainsDatabase.Database.DatabaseEntities;
using Reinforced.Lattice.Configuration;

namespace Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels
{
    public class TripViewModel
    {
        public Configurator<Trip, Trip> Configurator { get; set; }
    }

   /* public class TripRow
    {
        public int TripId { get; set; }
        public int TrainId { get; set; }
        public int RouteId { get; set; }
        public string RouteName { get; set; }
        public string DepatrureStationName { get; set; }
        public DateTime DepatrureDate { get; set; }
        public string ArrivalStationName { get; set; }
        public DateTime ArrivalDate { get; set; }
    }*/

    public static class TripTable
    {
        public static Configurator<Trip, Trip> Configure(this Configurator<Trip, Trip> conf)
        {
            conf.DefaultTable();
            conf.PrimaryKey(x => x.TripId);
          /*  conf.ProjectDataWith(x => x.Select(t => new TripRow()
            {
                TripId = t.TripId,
                RouteId = t.RouteId,
                RouteName = t.Route.RouteName,
                DepatrureStationName =
                    t.Route.RoutePoints.OrderBy(rp => rp.StationOrder).FirstOrDefault().Station.StationName,
                DepatrureDate = t.TripPoints.OrderBy(rp => rp.StationOrder).FirstOrDefault().DepartureTime,
                ArrivalStationName = t.Route.RoutePoints.OrderByDescending(rp => rp.StationOrder).FirstOrDefault()
                    .Station.StationName,
                ArrivalDate = t.TripPoints.OrderByDescending(rp => rp.StationOrder).FirstOrDefault().ArrivalTime

            }));*/
            return conf;
        }
    }
}

Nsu.Belov.TrainsDatabase.Web/Models/CrudViewModelsOLD/StationViewModel.cs
using Nsu.Belov.TrainsDatabase.Database.DatabaseEntities;
using Reinforced.Lattice.Configuration;

namespace Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels
{
    public class StationViewModel
    {
        public Configurator<Station, StationRow> Configurator { get; set; }
    }

    public class StationRow
    {
        public int StationId { get; set; }
        public string StationName { get; set; }
    }

    public static class StationTable
    {
        public static Configurator<Station, StationRow> Configure(this Configurator<Station, StationRow> conf)
        {
            conf.DefaultTable();
            conf.PrimaryKey(x => x.StationId);
            return conf;
        }
    }
}

Nsu.Belov.TrainsDatabase.Web/Models/CrudViewModelsOLD/TrainViewModel.cs
using Nsu.Belov.TrainsDatabase.Database.DatabaseEntities;
using Reinforced.Lattice.Configuration;

namespace Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels
{
    public class TrainViewModel
    {
        public Configurator<Train, TrainRow> Configurator { get; set; }
    }

    public class TrainRow
    {
        public int TrainId { get; set; }
        
//        public int Capacity { get; set; }
    }

    public static class TrainTable
    {
        public static Configurator<Train, TrainRow> Configure(this Configurator<Train, TrainRow> conf)
        {
            conf.DefaultTable();
            conf.PrimaryKey(x => x.TrainId);
            return conf;
        }
    }
}

Nsu.Belov.TrainsDatabase.Web/Controllers/CrudControllers/CrudController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Nsu.Belov.TrainsDatabase.Database;
using Nsu.Belov.TrainsDatabase.Database.DatabaseEntities;
using Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels;
using Reinforced.Lattice;
using Reinforced.Lattice.Adjustments;
using Reinforced.Lattice.Commands;
using Reinforced.Lattice.Configuration;
using Reinforced.Lattice.Editing;
using Reinforced.Lattice.Mvc;
using Reinforced.Lattice.Processing;

namespace Nsu.Belov.TrainsDatabase.Web.Controllers.CrudControllers
{
    public partial class CrudController : Controller
    {
        private readonly TrainsDataContext _context;

        public CrudController(TrainsDataContext context)
        {
            this._context = context;
        }

        public ActionResult RoutePoints()
        {
            var vm = new RoutePointViewModel()
            {
                Configurator = new Configurator<RoutePoint, RoutePoint>()
                    .Configure()
                    .Url(Url.Action(nameof(HandleRoutePoints)))
            };
            return View(vm);
        }

        public ActionResult HandleRoutePoints()
        {
            var conf = new Configurator<RoutePoint, RoutePoint>().Configure();
            var handler = conf.CreateMvcHandler(ControllerContext);
            handler.AddEditHandler(EditRoutePoint);
            handler.AddCommandHandler("Remove", RemoveRoutePoint);
            var routePoints = _context.RoutePoints
                .OrderBy(x => x.StationOrder);
            return handler.Handle(routePoints);
        }


        public TableAdjustment EditRoutePoint(LatticeData<RoutePoint, RoutePoint> latticeData,
            RoutePoint routePointRow)
        {
        RoutePoint routePoint = _context.RoutePoints
            .FirstOrDefault(x => x.RouteId == routePointRow.RouteId
                                 && x.StationOrder == routePointRow.StationOrder);

       
            if (routePoint == null)
            {
                routePoint = new RoutePoint
                {
                    RouteId = routePointRow.RouteId,
                    StationOrder = routePointRow.StationOrder
                };
                _context.RoutePoints.Add(routePoint);
            }
            else
            {
                routePoint = _context.RoutePoints
                    .FirstOrDefault(x =>
                        x.RouteId == routePointRow.RouteId && x.StationOrder == routePointRow.StationOrder);
            }
            

            try
            {
                routePoint.StationId = routePointRow.StationId;
                _context.SaveChanges();
            }
            catch (Exception e)
            {
                return latticeData.Adjust(x => x
                    .Message(LatticeMessage.User("failure", "Editing", $"Save exception: {e.Message}"))
                );
            }
            return latticeData.Adjust(x => x
                .UpdateRow(routePointRow)
                .Message(LatticeMessage.User("success", "Editing", "RoutePoint saved"))
            );
        }

        public TableAdjustment RemoveRoutePoint(LatticeData<RoutePoint, RoutePoint> latticeData)
        {
            var subj = latticeData.CommandSubject();
            var routePoint =
                _context.RoutePoints.FirstOrDefault(x =>
                    x.RouteId == subj.RouteId && x.StationOrder == subj.StationOrder);
            _context.RoutePoints.Remove(routePoint);
            _context.SaveChanges();
            return latticeData.Adjust(x => x
                .RemoveExact(subj)
                .Message(LatticeMessage.User("success", "Remove", "RoutePoint removed"))
            );
        }
    }
}

Nsu.Belov.TrainsDatabase.Web/Controllers/RoutesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Nsu.Belov.TrainsDatabase.Database;
using Nsu.Belov.TrainsDatabase.Database.DatabaseEntities;
using Nsu.Belov.TrainsDatabase.Web.Models;
using Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels;
using Reinforced.Lattice;
using Reinforced.Lattice.Adjustments;
using Reinforced.Lattice.Commands;
using Reinforced.Lattice.Configuration;
using Reinforced.Lattice.Editing;
using Reinforced.Lattice.Mvc;
using Reinforced.Lattice.Processing;

namespace Nsu.Belov.TrainsDatabase.Web.Controllers
{
    public class RoutesController : Controller
    {
        private readonly TrainsDataContext _context;

        public RoutesController(TrainsDataContext context)
        {
            _context = context;
        }

        public ActionResult Routes()
        {
            var vm = new Models.RouteViewModel()
            {
                Configurator = new Configurator<Route, RouteRow>()
                    .Configure()
                    .Url(Url.Action(nameof(HandleRoutes)))
            };
            return View(vm);
        }

        public ActionResult HandleRoutes()
        {
            var conf = new Configurator<Route, RouteRow>().Configure();
            var handler = conf.CreateMvcHandler(ControllerContext);
            handler.AddEditHandler(EditRoute);
            handler.AddCommandHandler("Remove", RemoveRoute);
            return handler.Handle(_context.Routes.OrderBy(x => x.RouteId));
        }

        public TableAdjustment EditRoute(LatticeData<Route, RouteRow> latticeData, RouteRow routeRow)
        {
            Route route;
            if (routeRow.RouteId == 0)
            {
                route = new Route();
                _context.Routes.Add(route);
            }
            else
            {
                route = _context.Routes
                    .FirstOrDefault(x => x.RouteId == routeRow.RouteId);
            }

            route.RouteName = routeRow.RouteName;
            _context.SaveChanges();
            routeRow.RouteId = route.RouteId;
            return latticeData.Adjust(x => x
                .Update(routeRow)
                .Message(LatticeMessage.User("success", "Editing", "Route saved"))
            );
        }

        public TableAdjustment RemoveRoute(LatticeData<Route, RouteRow> latticeData)
        {
            var subj = latticeData.CommandSubject();
            var route = _context.Routes.FirstOrDefault(x => x.RouteId == subj.RouteId);
            _context.Routes.Remove(route);
            _context.SaveChanges();
            return latticeData.Adjust(x => x
                .Remove(subj)
                .Message(LatticeMessage.User("success", "Remove", "Route removed"))
            );
        }

        public ActionResult RoutePointsForRoute(int routeId)
        {
            var vm = new Models.RoutePointViewModel()
            {
                SationsNames = (from station in _context.Stations
                    orderby station.StationId
                    select new SelectListItem()
                    {
                        Text = station.StationName,
                        Value = station.StationName
                    }).ToArray(),
                Configurator = new Configurator<RoutePoint, RoutePointRow>()
                    .Configure()
                    .Url(Url.Action(nameof(HandleRoutePoints), new {routeId}))
            };
            return View(vm);
        }

        public ActionResult HandleRoutePoints(int routeId)
        {
            var conf = new Configurator<RoutePoint, RoutePointRow>().Configure();
            var handler = conf.CreateMvcHandler(ControllerContext);
            handler.AddEditHandler((latticeData, rpRow) => EditRoutePoint(latticeData, rpRow, routeId));
            handler.AddCommandHandler("Remove", RemoveRoutePoint);
            var routePoints = _context.RoutePoints
                .Where(x => x.RouteId == routeId)
                .OrderBy(x => x.StationOrder);
            return handler.Handle(routePoints);
        }


        public TableAdjustment EditRoutePoint(LatticeData<RoutePoint, RoutePointRow> latticeData,
            RoutePointRow routePointRow, int routeId)
        {
            RoutePoint routePoint;
            if (routePointRow.RouteId == 0)
            {
                routePoint = new RoutePoint
                {
                    RouteId = routeId,
                    StationOrder = _context.RoutePoints.Where(x => x.RouteId == routeId)
                                       .Select(x => x.StationOrder)
                                       .DefaultIfEmpty(0)
                                       .Max() + 1
                };
                _context.RoutePoints.Add(routePoint);
            }
            else
            {
                routePoint = _context.RoutePoints
                    .FirstOrDefault(x => x.RouteId == routePointRow.RouteId
                                         && x.StationOrder == routePointRow.StationOrder);
            }

            Station station = _context.Stations.FirstOrDefault(x => x.StationName == routePointRow.StationName);

            if (station == null)
            {
                return latticeData.Adjust(x => x
                    .Message(LatticeMessage.User("failure", "Editing",
                        $"There is no station with name {routePointRow.StationName}"))
                );
            }


            if (_context.RoutePoints.Any(x => x.RouteId == routeId
                                              && x.StationOrder != routePoint.StationOrder
                                              && x.Station.StationId == station.StationId))
            {
                return latticeData.Adjust(x => x
                    .Message(LatticeMessage.User("failure", "Editing",
                        $"The route already has station {station.StationName}"))
                );
            }

            routePoint.Station = station;


            _context.SaveChanges();
            return latticeData.Adjust(x => x
                .Update(routePoint)
                .Message(LatticeMessage.User("success", "Editing", "Route saved"))
            );
        }

        public TableAdjustment RemoveRoutePoint(LatticeData<RoutePoint, RoutePointRow> latticeData)
        {
            var subj = latticeData.CommandSubject();
            if (_context.RoutePoints.Any(x => x.RouteId == subj.RouteId && x.StationOrder == subj.StationOrder + 1))
            {
                return latticeData.Adjust(x => x
                    .Message(LatticeMessage.User("failure", "Remove", "Can not delete point from the middle of route"))
                );
            }

            var routePoint =
                _context.RoutePoints.FirstOrDefault(x => x.RouteId == subj.RouteId
                                                         && x.StationOrder == subj.StationOrder);
            _context.RoutePoints.Remove(routePoint);
            _context.SaveChanges();
            return latticeData.Adjust(x => x
                .Remove(subj)
                .Message(LatticeMessage.User("success", "Remove", "RoutePoint removed"))
            );
        }
    }
}

Nsu.Belov.TrainsDatabase.Web/Views/Crudold/Routes.cshtml
@using Nsu.Belov.TrainsDatabase.Web.Models
@using Reinforced.Lattice.Commands
@using Reinforced.Lattice.Configuration
@using Reinforced.Lattice.Editing.Editors.PlainText
@using Reinforced.Lattice.Editing.Form
@using Reinforced.Lattice.Mvc
@using Reinforced.Lattice.Plugins.Toolbar
@using Reinforced.Lattice.Templates
@model Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels.RouteViewModel

@{
    ViewBag.Title = "Routes";
    var conf = Model.Configurator;
    conf.Column(x => x.RouteId)
        .Razor(@<a href="@Url.Action("RoutePointsForRoute", "Crud", new {routeId = "{RouteId}"})">{RouteId}</a>);

    conf.Column(x => x.RouteName)
        .Razor(@<a href="@Url.Action("RoutePointsForRoute", "Crud", new {routeId = "{RouteId}"})">{RouteName}</a>);
    conf.EditingForm(f =>
    {
        f.EditPlainText(x => x.RouteName);
        f.RenderTo("#ltcModal");
    }, c => c.Event("click").Selector("._beginEdit"));
    conf.Toolbar("toolbar-rt", x => { x.AddSimpleButton("Add new").AddNewByForm(); });
    conf.AddUiColumn<string>("Actions")
        .Razor(@<div>
                   <button class="btn btn-xs btn-warning _beginEdit">
                       <span class="glyphicon glyphicon-pencil"></span>
                   </button>
                   <button class="btn btn-xs btn-danger _remove">
                       <span class="glyphicon glyphicon-remove"></span>
                   </button>
               </div>)
        .SubscribeCellEvent(x => x.Command("click", "Remove").Selector("._remove"))
        ;
    conf.Command("Remove", x => x.ConfigureRemoval());
}

<h2>Маршруты</h2>

<div id="table"></div>

@section scripts {
    @{ Html.RenderPartial("DeleteTemplate"); }
    @* Render our templates *@
    @{ Html.RenderTemplates("lt", "Lattice_Templates_Bootstrap"); }

    @* Instantiate our table and put it to JS window.$$table variable *@
    @Model.Configurator.InitializationScript("table", "window.$$table")
}

Nsu.Belov.TrainsDatabase.Web/Views/Crudold/Stations.cshtml
@using Reinforced.Lattice.Configuration
@using Reinforced.Lattice.Editing.Editors.PlainText
@using Reinforced.Lattice.Editing.Form
@using Reinforced.Lattice.Mvc
@using Reinforced.Lattice.Plugins.Toolbar
@using Reinforced.Lattice.Templates
@model Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels.StationViewModel

@{
    ViewBag.Title = "Станции";
    var conf = Model.Configurator;
    conf.EditingForm(f =>
    {
        f.EditPlainText(x => x.StationName); 
        f.RenderTo("#ltcModal");
    }, c => c.Event("click").Selector("._beginEdit"));
    conf.Toolbar("toolbar-rt", x => { x.AddSimpleButton("Add new").AddNewByForm(); });
    conf.AddUiColumn<string>("Actions")
        .Razor(@<div>
                   <button class="btn btn-xs btn-warning _beginEdit">
                       <span class="glyphicon glyphicon-pencil"></span>
                   </button>
                   <button class="btn btn-xs btn-danger _remove">
                       <span class="glyphicon glyphicon-remove"></span>
                   </button>
               </div>)
        .SubscribeCellEvent(x => x.Command("click", "Remove").Selector("._remove"))
        ;
}

<div id="table"></div>

@section scripts {
    @* Render our templates *@
    @{ Html.RenderTemplates("lt", "Lattice_Templates_Bootstrap"); }

    @* Instantiate our table and put it to JS window.$$table variable *@
    @Model.Configurator.InitializationScript("table", "window.$$table")
}

Nsu.Belov.TrainsDatabase.Web/Views/Crudold/Trains.cshtml
@using Reinforced.Lattice.Configuration
@using Reinforced.Lattice.Editing.Editors.PlainText
@using Reinforced.Lattice.Editing.Form
@using Reinforced.Lattice.Mvc
@using Reinforced.Lattice.Plugins.Toolbar
@using Reinforced.Lattice.Templates
@model Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels.TrainViewModel


@{
    ViewBag.Title = "Поезда";
    var conf = Model.Configurator;
    conf.EditingForm(f =>
    {
//        f.EditPlainText(x => x.Capacity);
//        f.EditPlainText(x => x.Category);
        f.RenderTo("#ltcModal");
    }, c => c.Event("click").Selector("._beginEdit"));
    conf.Toolbar("toolbar-rt", x => { x.AddSimpleButton("Add new").AddNewByForm(); });
    conf.AddUiColumn<string>("Actions")
        .Razor(@<div>
    <button class="btn btn-xs btn-warning _beginEdit">
        <span class="glyphicon glyphicon-pencil"></span>
    </button>
    <button class="btn btn-xs btn-danger _remove">
        <span class="glyphicon glyphicon-remove"></span>
    </button>
</div>)
.SubscribeCellEvent(x => x.Command("click", "Remove").Selector("._remove"))
;
}

<div id="table"></div>

@section scripts {
    @* Render our templates *@
    @{ Html.RenderTemplates("lt", "Lattice_Templates_Bootstrap"); }

    @* Instantiate our table and put it to JS window.$$table variable *@
    @Model.Configurator.InitializationScript("table", "window.$$table")
}

Nsu.Belov.TrainsDatabase.Web/Views/Crudold/TripPoints.cshtml
@using Nsu.Belov.TrainsDatabase.Web.Models
@using Reinforced.Lattice.CellTemplating
@using Reinforced.Lattice.Commands
@using Reinforced.Lattice.Configuration
@using Reinforced.Lattice.Editing.Editors.PlainText
@using Reinforced.Lattice.Editing.Form
@using Reinforced.Lattice.Filters
@using Reinforced.Lattice.Filters.Value
@using Reinforced.Lattice.Mvc
@using Reinforced.Lattice.Plugins.Toolbar
@using Reinforced.Lattice.Templates
@model Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels.TripPointViewModel

@{
    ViewBag.Title = "TripPoints";
    var conf = Model.Configurator;
    conf.Column(x => x.ArrivalTime).Format("`parseDateTime({#})`");
    conf.Column(x => x.DepartureTime).Format("`parseDateTime({#})`");
    conf.EditingForm(f =>
    {
        f.EditPlainText(x => x.TripId);
        f.EditPlainText(x => x.StationOrder);
        f.EditPlainText(x => x.ArrivalTime);
        f.EditPlainText(x => x.DepartureTime);
        f.EditPlainText(x => x.FirstClassSeats);
        f.EditPlainText(x => x.SecondClassSeats);
        f.RenderTo("#ltcModal");
    }, c => c.Event("click").Selector("._beginEdit"));
    conf.Toolbar("toolbar-rt", x => { x.AddSimpleButton("Add new").AddNewByForm(); });
    conf.AddUiColumn<string>("Actions")
        .Razor(@<div>
                   <button class="btn btn-xs btn-warning _beginEdit">
                       <span class="glyphicon glyphicon-pencil"></span>
                   </button>
                   <button class="btn btn-xs btn-danger _remove">
                       <span class="glyphicon glyphicon-remove"></span>
                   </button>
               </div>)
        .SubscribeCellEvent(x => x.Command("click", "Remove").Selector("._remove"));
    conf.Command("Remove", x => x.ConfigureRemoval());

    conf.Column(x => x.TripId).FilterValueUi(ui => ui.ClientFiltering());
    conf.Column(x => x.StationOrder).FilterValueUi(ui => ui.ClientFiltering());
    conf.Column(x => x.ArrivalTime).FilterValueUi(ui => ui.CompareOnlyDates().ClientFiltering());
    conf.Column(x => x.DepartureTime).FilterValueUi(ui => ui.CompareOnlyDates().ClientFiltering());
    conf.Column(x => x.FirstClassSeats).FilterValueUi(ui => ui.ClientFiltering());
    conf.Column(x => x.SecondClassSeats).FilterValueUi(ui => ui.ClientFiltering());
  
}

<h2>TripPoints</h2>

<div id="table"></div>

@section scripts {
    @{ Html.RenderPartial("DeleteTemplate"); }
    @* Render our templates *@
    @{ Html.RenderTemplates("lt", "Lattice_Templates_Bootstrap"); }

    @* Instantiate our table and put it to JS window.$$table variable *@
    @Model.Configurator.InitializationScript("table", "window.$$table")
}

Nsu.Belov.TrainsDatabase.Web/Views/Crudold/Trips.cshtml
@using Nsu.Belov.TrainsDatabase.Web.Models
@using Reinforced.Lattice.Commands
@using Reinforced.Lattice.Configuration
@using Reinforced.Lattice.Editing.Editors.PlainText
@using Reinforced.Lattice.Editing.Form
@using Reinforced.Lattice.Mvc
@using Reinforced.Lattice.Plugins.Toolbar
@using Reinforced.Lattice.Templates
@model Nsu.Belov.TrainsDatabase.Web.Models.CrudViewModels.TripViewModel


@{
    ViewBag.Title = "Routes";
    var conf = Model.Configurator;
    conf.Column(x => x.RouteId)
        .Razor(@<a href="@Url.Action("RoutePointsForRoute", "Crud", new {routeId = "{RouteId}"})">{RouteId}</a>);


    conf.EditingForm(f =>
    {
        f.EditPlainText(t => t.TripId);
        f.EditPlainText(t => t.RouteId);
        f.EditPlainText(t => t.TrainId);
        f.RenderTo("#ltcModal");
    }, c => c.Event("click").Selector("._beginEdit"));
    conf.Toolbar("toolbar-rt", x => { x.AddSimpleButton("Add new").AddNewByForm(); });
    conf.AddUiColumn<string>("Actions")
        .Razor(@<div>
                   <button class="btn btn-xs btn-warning _beginEdit">
                       <span class="glyphicon glyphicon-pencil"></span>
                   </button>
                   <button class="btn btn-xs btn-danger _remove">
                       <span class="glyphicon glyphicon-remove"></span>
                   </button>
               </div>)
        .SubscribeCellEvent(x => x.Command("click", "Remove").Selector("._remove"))
        ;
    conf.Command("Remove", x => x.ConfigureRemoval());
}

<h2>Маршруты</h2>

<div id="table"></div>

@section scripts {
    @{ Html.RenderPartial("DeleteTemplate"); }
    @* Render our templates *@
    @{ Html.RenderTemplates("lt", "Lattice_Templates_Bootstrap"); }

    @* Instantiate our table and put it to JS window.$$table variable *@
    @Model.Configurator.InitializationScript("table", "window.$$table")
}